# route the build to the container-based infrastructure for a faster build
sudo: false
language: ruby
rvm:
  - 2.2.5

env:
  global:
    # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem install jekyll
  - gem install html-proofer

# build and validate HTML files
# more info at https://github.com/gjtorikian/html-proofer
script: jekyll build && htmlproofer ./_site --alt-ignore '/.*/'

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
